version: 2

models:
  - name: student_enrollments
    columns:
      - name: enrollment_id
        tests:
          - unique
          - not_null
      - name: student_id
        tests:
          - not_null
      - name: course_id
        tests:
          - not_null
      - name: batch_id
        tests:
          - not_null
      - name: student_name
        tests:
          - not_null
  - name: enrollment_messages
    tests: 
      - duplicate_messages
    columns:
      - name: message_id
        tests:
          - not_null
      - name: activity_status
        tests:
          - not_null
          - accepted_values:
              values: ['Activity_Sent', 'Activity_Access', 'Activity_Submission']
      - name: enrollment_id
        tests:
          - not_null
      - name: student_id
        tests:
          - not_null
      - name: course_id
        tests:
          - not_null
      - name: batch_id
        tests:
          - not_null
      - name: student_name
        tests:
          - not_null
  - name: school_access_rates
    columns:
      - name: school_name
        tests:
          - unique
          - not_null
      - name: total_students
        tests:
          - not_null
      - name: students_with_any_access
        tests:
          - not_null
      - name: total_activities_sent
        tests:
          - not_null
      - name: total_activities_accessed
        tests:
          - not_null
      - name: school_access_rate_pct
        tests:
          - not_null