name: 'tap'
version: '1.0.0'
config-version: 2

profile: 'tap'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  tap:
    +tags: ["activity_funnel"]
    bronze:
      +schema: bronze
      +tags: ["bronze"]
    silver:
      +schema: silver
      +tags: ["silver"]
      +materialized: table
    gold:
      +schema: gold
      +tags: ["gold"]
      +materialized: table
