sources:
    - name: glific
      description: Tables here have the TAP glific bigquery data
      schema: "MEL_2025_26"
      tables:
          - name: messages
            identifier: messages
            description: This has the raw messages data from the TAP buddy
          - name: contacts
            identifier: contacts
            description: This has the raw contacts data from the TAP buddy